export const products = [
  {
    id: "1",
    name: "Hand-Painted Blue Pottery Vase",
    price: 3450,
    originalPrice: 4200,
    rating: 4.9,
    reviews: 48,
    artisan: "Laxman Singh",
    artisanLocation: "Jaipur, Rajasthan",
    category: "Pottery",
    material: "Quartz & Glass Powder",
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&q=80",
    badge: "Verified Artisan",
    isNew: false,
    isFeatured: true,
    stock: 3,
    description:
      "A masterpiece from the ancient blue pottery tradition of Jaipur. Each vase is hand-painted using natural mineral pigments and fired at precise temperatures. No two pieces are identical.",
  },
  {
    id: "2",
    name: "Banarasi Silk Stole – Sunset Bloom",
    price: 5800,
    originalPrice: 7500,
    rating: 5.0,
    reviews: 112,
    artisan: "Kamala Devi",
    artisanLocation: "Varanasi, UP",
    category: "Textiles",
    material: "Hand-spun Silk",
    image: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=600&q=80",
    badge: "Verified Artisan",
    isNew: false,
    isFeatured: true,
    stock: 7,
    description:
      "Woven on a traditional handloom, this stole features a classic zari border with floral motifs passed down through five generations of the Devi weaving family.",
  },
  {
    id: "3",
    name: "Dhokra Brass Elephant Figurine",
    price: 2100,
    originalPrice: 2100,
    rating: 4.8,
    reviews: 67,
    artisan: "Raju Mistri",
    artisanLocation: "Bastar, Chhattisgarh",
    category: "Metal Craft",
    material: "Brass (Lost-Wax Cast)",
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80",
    badge: "Verified Artisan",
    isNew: true,
    isFeatured: false,
    stock: 12,
    description:
      "Crafted using the ancient Dhokra lost-wax casting technique, this elephant figurine captures the raw beauty of tribal artistry from Chhattisgarh.",
  },
  {
    id: "4",
    name: "Madhubani Painting – Peacock Dance",
    price: 6200,
    originalPrice: 6200,
    rating: 4.7,
    reviews: 29,
    artisan: "Sunita Devi",
    artisanLocation: "Madhubani, Bihar",
    category: "Paintings",
    material: "Natural Pigments on Handmade Paper",
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&q=80",
    badge: "Master Artisan",
    isNew: true,
    isFeatured: true,
    stock: 1,
    description:
      "A stunning Madhubani painting depicting a peacock dance, rendered in natural earth pigments. This piece took 12 days to complete and tells the story of the monsoon season.",
  },
  {
    id: "5",
    name: "Terracotta Wind Chime – Floral Bell",
    price: 890,
    originalPrice: 1200,
    rating: 4.6,
    reviews: 93,
    artisan: "Priya Kumari",
    artisanLocation: "Khurja, UP",
    category: "Pottery",
    material: "Sun-dried Terracotta",
    image: "https://images.unsplash.com/photo-1525909002-1b05e0c869d8?w=600&q=80",
    badge: "Verified Artisan",
    isNew: false,
    isFeatured: false,
    stock: 25,
    description:
      "Hand-shaped terracotta bells painted with natural dyes, producing a soft, earthy tone. Perfect for balconies or as a mindful home accent.",
  },
  {
    id: "6",
    name: "Teakwood Carved Wall Art – Tree of Life",
    price: 8900,
    originalPrice: 11000,
    rating: 5.0,
    reviews: 18,
    artisan: "Mohan Vaidya",
    artisanLocation: "Jodhpur, Rajasthan",
    category: "Wood Craft",
    material: "Reclaimed Teak",
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    badge: "Master Artisan",
    isNew: false,
    isFeatured: true,
    stock: 2,
    description:
      "Intricately carved from a single piece of reclaimed teak, this wall panel features the iconic Tree of Life motif — a symbol of growth, connection, and natural beauty.",
  },
  {
    id: "7",
    name: "Pashmina Shawl – Natural Ivory",
    price: 12500,
    originalPrice: 15000,
    rating: 4.9,
    reviews: 54,
    artisan: "Farida Khatun",
    artisanLocation: "Srinagar, J&K",
    category: "Textiles",
    material: "Grade A Pashmina",
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=600&q=80",
    badge: "Verified Artisan",
    isNew: false,
    isFeatured: false,
    stock: 4,
    description:
      "100% pure Pashmina, hand-combed from Himalayan Changthangi goats and hand-spun on a charkha. Soft enough to pass through a ring, warm enough for Himalayan winters.",
  },
  {
    id: "8",
    name: "Warli Tribal Art Print – Village Life",
    price: 1800,
    originalPrice: 1800,
    rating: 4.7,
    reviews: 76,
    artisan: "Balu Vitthal",
    artisanLocation: "Palghar, Maharashtra",
    category: "Paintings",
    material: "Rice Paste on Dark Canvas",
    image: "https://images.unsplash.com/photo-1541961017774-22349e4a1262?w=600&q=80",
    badge: "Verified Artisan",
    isNew: true,
    isFeatured: false,
    stock: 8,
    description:
      "Traditional Warli tribal art depicting the rhythms of village life: harvesting, dancing, and celebrating. Made using white rice paste on a dark canvas.",
  },
];

export const categories = [
  {
    id: "textiles",
    name: "Hand-woven Textiles",
    count: 120,
    image: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=500&q=80",
    color: "#f4a460",
  },
  {
    id: "pottery",
    name: "Terracotta & Pottery",
    count: 85,
    image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=500&q=80",
    color: "#fc9f66",
  },
  {
    id: "paintings",
    name: "Folk Paintings",
    count: 64,
    image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=500&q=80",
    color: "#97f3b5",
  },
  {
    id: "wood",
    name: "Wooden Crafts",
    count: 45,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500&q=80",
    color: "#d8c3b4",
  },
  {
    id: "metal",
    name: "Metal & Brass",
    count: 38,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500&q=80",
    color: "#ffdcc3",
  },
  {
    id: "jewelry",
    name: "Tribal Jewelry",
    count: 92,
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=500&q=80",
    color: "#ffb77d",
  },
];

export const artisans = [
  {
    id: "1",
    name: "Kamala Devi",
    craft: "Indigo Weaver",
    location: "Varanasi, UP",
    avatar: "https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=200&q=80",
    story:
      "After my husband fell ill, weaving became my lifeline. Each thread I weave is a prayer for my family.",
    products: 14,
    rating: 4.9,
    certified: true,
    yearsActive: 12,
  },
  {
    id: "2",
    name: "Sunita Devi",
    craft: "Madhubani Painter",
    location: "Bihar",
    avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200&q=80",
    story:
      "Each pattern is inspired by the flora in my backyard. I paint what nature tells me each morning.",
    products: 9,
    rating: 5.0,
    certified: true,
    yearsActive: 8,
  },
  {
    id: "3",
    name: "Laxman Singh",
    craft: "Blue Pottery Master",
    location: "Jaipur, Rajasthan",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&q=80",
    story:
      "My family has practiced this art for 40 years. I am the third generation, and I teach my sons now.",
    products: 22,
    rating: 4.9,
    certified: true,
    yearsActive: 18,
  },
];

export const testimonials = [
  {
    id: "1",
    name: "Ananya P.",
    location: "Mumbai",
    rating: 5,
    text: "The Banarasi silk stole I ordered arrived beautifully packed. The quality is beyond anything I could find locally. Knowing I'm supporting a real artisan family makes it even more special.",
    product: "Banarasi Silk Stole",
    verified: true,
  },
  {
    id: "2",
    name: "Rohan M.",
    location: "Bangalore",
    rating: 5,
    text: "I've bought from SellWhatUMade three times now. Every piece tells a story. The sustainability mission resonates deeply with me — this is how e-commerce should work.",
    product: "Teakwood Wall Art",
    verified: true,
  },
  {
    id: "3",
    name: "Sneha L.",
    location: "Delhi",
    rating: 5,
    text: "Bought the Madhubani painting as a housewarming gift. My friends couldn't believe it was handmade. The whole experience — from browsing to delivery — was flawless.",
    product: "Madhubani Painting",
    verified: true,
  },
];

export const orders = [
  {
    id: "#AD-9284",
    product: "Hand-woven Terracotta Vase",
    productImage: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=80&q=80",
    quantity: 1,
    customer: "Priya Deshmukh",
    location: "Mumbai, MH",
    status: "New" as const,
    amount: 3450,
    date: "2024-06-08",
  },
  {
    id: "#AD-9271",
    product: "Carved Rosewood Elephant",
    productImage: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=80&q=80",
    quantity: 2,
    customer: "James Wilson",
    location: "Bangalore, KA",
    status: "Processing" as const,
    amount: 4200,
    date: "2024-06-07",
  },
  {
    id: "#AD-9265",
    product: "Indigo Block-Print Stole",
    productImage: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=80&q=80",
    quantity: 1,
    customer: "Ananya Roy",
    location: "Kolkata, WB",
    status: "Shipped" as const,
    amount: 5800,
    date: "2024-06-06",
  },
  {
    id: "#AD-9260",
    product: "Hand-beaten Brass Earrings",
    productImage: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=80&q=80",
    quantity: 3,
    customer: "Michael Scott",
    location: "Delhi, DL",
    status: "Processing" as const,
    amount: 2700,
    date: "2024-06-05",
  },
  {
    id: "#AD-9251",
    product: "Madhubani Wall Art",
    productImage: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=80&q=80",
    quantity: 1,
    customer: "Rahul Verma",
    location: "Hyderabad, TS",
    status: "Delivered" as const,
    amount: 6200,
    date: "2024-06-04",
  },
];
